const express = require('express')

const axieRouter = require('@controllers/axie')
const playerRouter = require('@controllers/player')
const auctionRouter = require('@controllers/auction')
const leaderboardRouter = require('@controllers/leaderboard')
const exchangeRouter = require('@controllers/exchange')
const cardsRouter = require('@controllers/gameData/classic/cards/v1')
const statsRouter = require('@controllers/gameData/classic/stats')
const effectsRouter = require('@controllers/gameData/classic/effects')
const endpoints = require('@utils/v1-endpoints')

const router = express.Router()
router.use('/info', (req, res) => res.json({ error: 'deprecated' }))
router.use('/version', (req, res) => res.json({ version: '1.0.10' }))
router.use('/endpoints', (req, res) => res.json(endpoints))
router.use('/axie', axieRouter)
router.use('/player', playerRouter)
router.use('/auction', auctionRouter)
router.use('/leaderboard', leaderboardRouter)
router.use('/exchange', exchangeRouter)
router.use('/cards', cardsRouter)
router.use('/stats', statsRouter)
router.use('/effects', effectsRouter)

module.exports = router
